title: Cool & Ready Design System
description: Brand & design system for B2B seafood supply chain
theme: jekyll-theme-minimal
show_downloads: false
github:
  repository_url: https://github.com/Nsc-source/cool-and-ready-design-system
  is_project_page: true
